export const statusCode = {
    STATUS_OK: 200,
    STATUS_CREATED: 201,
    STATUS_NO_CONTENT: 204,
    STATUS_READY_FOR_SIGN_UP: 230,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_FORBIDDEN: 403,
    STATUS_NOT_FOUND: 404,
    STATUS_LOGIN_FAILED: 401,
    STATUS_TOO_MANY_REQUEST: 429,
    STATUS_USER_ALREADY_EXISTS: 432,
    STATUS_USER_DOES_NOT_EXIST: 433,
    STATUS_USER_NOT_VERIFIED: 434,
    STATUS_INTERNAL_SERVER_ERROR: 500
}; 